---
name: Actions Workflow

on: 
  # push:
  schedule:
    - cron: '4 17 * * *'
  pull_request: 
    types: [closed, assigned, opened, reopened]
  

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: See Lists
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v4
      - name: See Lists After Checkout
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Hari
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
